# Generated by Django 6.0 on 2026-02-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                ("phone_number", models.CharField(max_length=20, verbose_name="Номер телефона")),
                ("email", models.EmailField(max_length=254, verbose_name="Электронная почта")),
            ],
            options={
                "verbose_name": "Контактная информация",
                "verbose_name_plural": "Контактная информация",
            },
        ),
    ]
