# Generated by Django 6.0 on 2026-02-17 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_options_product_is_published_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_published",
        ),
    ]
